Bahmni/openmrs-module-fhir2Extension

- omod/src/main/resources/webModuleApplicationContext.xml
- pom.xml
This PR is about:
- Upgrading openmrs to 2.4.2
- Upgrades fhir2 version to 1.4.0
- Updates annotations as per spring5
> BAH-1954 - Upgrade OpenMRS version from 2.1.6 to 2.4.2

- api/src/main/java/org/openmrs/module/fhirExtension/service/ObsBasedDiagnosticReportService.java
- api/src/main/java/org/openmrs/module/fhirExtension/service/OrderUpdateService.java
- api/src/main/java/org/openmrs/module/fhirExtension/validators/DiagnosticReportRequestValidator.java
- api/src/test/java/org/openmrs/module/fhirExtension/service/ObsBasedDiagnosticReportServiceTest.java
- api/src/test/java/org/openmrs/module/fhirExtension/service/OrderUpdateServiceTest.java
- api/src/test/java/org/openmrs/module/fhirExtension/validators/DiagnosticReportRequestValidatorTest.java
JIRA link - https://bahmni.atlassian.net/jira/software/c/projects/BAH/boards/35?modal=detail&selectedIssue=BAH-2015
Summary - To update fulfiller status as COMPLETED once a report is uploaded against a lab order
> BAH-2015 | Closing of open orders

- api/pom.xml
Adding Jacoco Plugin to fhir2Extension-api
> Adding Jacoco Plugin

- pom.xml
Jira link: https://bahmni.atlassian.net/browse/BAH-2138?atlOrigin=eyJpIjoiODBhZDQ4NTJjMjc4NDYyZjgyNjNkZGFjMTk3NDkzM2QiLCJwIjoiaiJ9
> BAH-2138 | upgrade. fhir2 snapshot version

- api/src/main/java/org/openmrs/module/fhirExtension/service/ObsBasedDiagnosticReportService.java
- api/src/test/java/org/openmrs/module/fhirExtension/service/ObsBasedDiagnosticReportServiceTest.java
Issue link : https://bahmni.atlassian.net/browse/BAH-2424?atlOrigin=eyJpIjoiZTc5YzJiNGQxNDE1NDJlOTljZGM3NjQ3MjUzZDY3MTAiLCJwIjoiaiJ9
> BAH-2424 | fix. Lab report upload failing for some patients

- pom.xml
Jira: https://bahmni.atlassian.net/browse/BAH-2718?atlOrigin=eyJpIjoiMTNlOGQzYjRlMDgwNDM2Nzk4ZGE1MmMyNzM0MzNhZWIiLCJwIjoiaiJ9
> BAH-2718 | update. fhir2-omod version

- api/pom.xml
- omod/pom.xml
- pom.xml
JIRA card -> https://bahmni.atlassian.net/browse/BAH-2849
> Bindu | BAH-2849 | Release 1.1.0 onto Nexus

- api/pom.xml
- api/src/main/java/org/openmrs/module/fhirExtension/domain/observation/LabResult.java
- api/src/main/java/org/openmrs/module/fhirExtension/service/ObsBasedDiagnosticReportService.java
- api/src/main/java/org/openmrs/module/fhirExtension/translators/impl/DiagnosticReportObsLabResultTranslatorImpl.java
- api/src/test/java/org/openmrs/module/fhirExtension/service/ObsBasedDiagnosticReportServiceTest.java
- omod/pom.xml
- pom.xml
Jira link: https://bahmni.atlassian.net/browse/BAH-2998?atlOrigin=eyJpIjoiMjIyYWNhMzlkM2Y1NGRlMzkzYzFkOGVkNzM5M2ZhZjkiLCJwIjoiaiJ9
Summary:
1. This PR has changes to save the test result value which has the data type as 'Numeric'
2. This PR doesn't cover capturing test result for Panel
3. This Save will work only if attachment is not present. Both attachment and value will not be saved.
4. This PR doesn't take care of Abnormal result.
> BAH-2998 | Add. Functionality to capture test result 

- pom.xml
JIRA https://bahmni.atlassian.net/browse/BAH-3110
> BAH-3110 | Upgrading OpenMRS version to 2.5.12

- api/src/main/java/org/openmrs/module/fhirExtension/export/impl/ConditionExport.java
- api/src/main/java/org/openmrs/module/fhirExtension/export/impl/DiagnosisExport.java
- api/src/main/java/org/openmrs/module/fhirExtension/service/ExportTask.java
- api/src/main/java/org/openmrs/module/fhirExtension/service/impl/ExportTaskImpl.java
- api/src/test/java/org/openmrs/module/fhirExtension/service/impl/ExportTaskTest.java
- omod/src/main/java/org/openmrs/module/fhirExtension/web/ExportController.java
- omod/src/test/java/org/openmrs/module/fhirExtension/web/ExportControllerTest.java
JIRA : https://bahmni.atlassian.net/browse/BS-188
Summary
---------
- Handle Date validation even before creating FHIR task
- Adding `category` to the FHIR Condition resource
> BS-188 | Adding category to Condition, Validating parameters

- api/src/main/java/org/openmrs/module/fhirExtension/service/ExportTask.java
- api/src/main/java/org/openmrs/module/fhirExtension/service/impl/ExportTaskImpl.java
- api/src/test/java/org/openmrs/module/fhirExtension/service/impl/ExportTaskTest.java
- omod/src/main/java/org/openmrs/module/fhirExtension/web/ExportController.java
- omod/src/test/java/org/openmrs/module/fhirExtension/web/ExportControllerTest.java
JIRA - https://bahmni.atlassian.net/browse/BS-188
Summary
----------
- Validating Start date on or before end date
> BS-188 | Validating start date before end date

- .github/workflows/build_publish.yml
- .github/workflows/validate_pr.yml
JIRA - https://bahmni.atlassian.net/browse/BS-206
> BS-206 | Updating GHA for SNOMED master branch

- api/src/main/java/org/openmrs/module/fhirExtension/export/anonymise/handler/AnonymiseHandler.java
- api/src/test/resources/FHIR Export/config/anonymise-fhir.json
- Changing method name for BirthDate and DeceasedDateTime to `firstOfMonth`
> Changing method name to firstOfMonth for BirthDate, DeceasedDate

- api/src/main/java/org/openmrs/module/fhirExtension/service/ExportAsyncService.java
- api/src/main/java/org/openmrs/module/fhirExtension/service/impl/ExportTaskImpl.java
- api/src/test/java/org/openmrs/module/fhirExtension/service/ExportAsyncServiceTest.java
FHIR Export Admin UI
https://bahmni.atlassian.net/browse/BS-247
> BS 247 - FHIR Export Admin UI

- api/src/main/java/org/openmrs/module/fhirExtension/export/anonymise/impl/IdResourceCorrelate.java
- api/src/main/java/org/openmrs/module/fhirExtension/export/anonymise/impl/IdentifierResourceRedact.java
- api/src/test/java/org/openmrs/module/fhirExtension/export/anonymise/handler/AnonymiseHandlerTest.java
Correlation and Redact remove sensitive information
https://bahmni.atlassian.net/browse/BS-271
> BS-271 | Vijay | Correlation and Redact remove sensitive information

- api/src/main/java/org/openmrs/module/fhirExtension/service/ExportAsyncService.java
- api/src/main/java/org/openmrs/module/fhirExtension/service/ExportTask.java
- api/src/main/java/org/openmrs/module/fhirExtension/service/impl/ExportTaskImpl.java
- api/src/main/resources/moduleApplicationContext.xml
- api/src/test/java/org/openmrs/module/fhirExtension/service/ExportAsyncServiceTest.java
- api/src/test/java/org/openmrs/module/fhirExtension/service/impl/ExportTaskTest.java
- omod/src/main/java/org/openmrs/module/fhirExtension/web/ExportController.java
- omod/src/test/java/org/openmrs/module/fhirExtension/web/ExportControllerTest.java
add User Name, Start Date and End Date as part of initialize
https://bahmni.atlassian.net/browse/BS-291
> BS-291 | Vijay | add User Name, Start Date and End Date as part of initialize

- api/src/main/java/org/openmrs/module/fhirExtension/service/impl/ExportTaskImpl.java
- api/src/test/java/org/openmrs/module/fhirExtension/service/impl/ExportTaskTest.java
Filter only FHIR Export tasks in Admin FHIR Export UI
https://bahmni.atlassian.net/browse/BS-292
> BS-292 | Vijay, Siva | Tagging FHIR Export Task

- README.md
Jira - https://bahmni.atlassian.net/browse/BS-289
- Added a Configuration section describing FHIR export path config.
> BS-289 | Update the README

- README.md
BS-289 | Patrick | update readme
> BS-289 | Update the README (#45)

- .github/workflows/validate_pr.yml
- api/src/main/java/org/openmrs/module/fhirExtension/dao/TaskDao.java
- api/src/main/java/org/openmrs/module/fhirExtension/dao/impl/TaskDaoImpl.java
- api/src/main/java/org/openmrs/module/fhirExtension/service/TaskService.java
- api/src/main/java/org/openmrs/module/fhirExtension/service/impl/TaskServiceImpl.java
- api/src/test/java/org/openmrs/module/fhirExtension/dao/impl/TaskDaoImplTest.java
- api/src/test/java/org/openmrs/module/fhirExtension/service/impl/TaskServiceImplTest.java
- omod/src/main/java/org/openmrs/module/fhirExtension/web/TaskController.java
- omod/src/main/java/org/openmrs/module/fhirExtension/web/contract/PatientTaskResponse.java
- omod/src/main/java/org/openmrs/module/fhirExtension/web/mapper/TaskMapper.java
https://app.asana.com/0/1204322126657135/1206860834641289
> A-1206860834641289 | Get API to fetch NON-MEDICATION TASKS of Patient's Active Visit

- api/src/main/resources/liquibase.xml
Kavitha | Add db migration changes for concept nursing_activity_system
> Kavitha | Add db migration changes for concept nursing_activity_system

- omod/src/main/java/org/openmrs/module/fhirExtension/web/contract/TaskRequest.java
- omod/src/main/java/org/openmrs/module/fhirExtension/web/contract/TaskResponse.java
- omod/src/main/java/org/openmrs/module/fhirExtension/web/mapper/TaskMapper.java
Add notes columns to allow ability to add task notes
> Add notes columns to allow ability to add task notes

- api/src/main/java/org/openmrs/module/fhirExtension/dao/impl/TaskDaoImpl.java
- api/src/main/java/org/openmrs/module/fhirExtension/service/TaskService.java
- api/src/main/java/org/openmrs/module/fhirExtension/service/impl/TaskServiceImpl.java
- omod/src/main/java/org/openmrs/module/fhirExtension/web/TaskController.java
- omod/src/main/java/org/openmrs/module/fhirExtension/web/contract/PatientTaskResponse.java
- omod/src/main/java/org/openmrs/module/fhirExtension/web/contract/TaskRequest.java
- omod/src/main/java/org/openmrs/module/fhirExtension/web/contract/TaskResponse.java
- omod/src/main/java/org/openmrs/module/fhirExtension/web/contract/TaskUpdateRequest.java
- omod/src/main/java/org/openmrs/module/fhirExtension/web/mapper/TaskMapper.java
Refactor Changes | Used Visit Instead of Patient in for reference
> Refactor Changes | Used Visit Instead of Patient in for reference

- api/src/main/java/org/openmrs/module/fhirExtension/dao/TaskDao.java
- api/src/main/java/org/openmrs/module/fhirExtension/dao/TaskRequestedPeriodDao.java
- api/src/main/java/org/openmrs/module/fhirExtension/dao/impl/TaskDaoImpl.java
- api/src/main/java/org/openmrs/module/fhirExtension/dao/impl/TaskRequestedPeriodDaoImpl.java
- api/src/main/java/org/openmrs/module/fhirExtension/service/TaskService.java
- api/src/main/java/org/openmrs/module/fhirExtension/service/impl/TaskServiceImpl.java
- api/src/test/java/org/openmrs/module/fhirExtension/service/impl/TaskServiceImplTest.java
Create DAO methods for shift start and rollover task, bulk creation and updation.
Asana Link:
Shift Start Task: https://app.asana.com/0/1204322126657135/1206987173547140/f
Rollover task: https://app.asana.com/0/1204322126657135/1206987173547144/f
> Create DAO methods for task creation and updation

- api/src/main/java/org/openmrs/module/fhirExtension/dao/impl/TaskDaoImpl.java
Task not loading in Ward Level dashboard issue fix
> Task not loading in Ward Level dashboard issue fix

- omod/src/main/java/org/openmrs/module/fhirExtension/web/mapper/TaskMapper.java
card - https://bahmni.atlassian.net/browse/BAH-4101
> BAH-4101|refactor fetch concept names for task creation
